version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/jobmaster
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Quocviet2003@
    volumes:
      - ./uploads:/uploads  # Mount thư mục uploads từ máy chủ vào container

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=jobmaster
      - MYSQL_ROOT_PASSWORD=Quocviet2003@
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    command:
      --bind-address=0.0.0.0

volumes:
  db-data:
